server:
 port: 8085
 
spring:
 datasource:
  url: jdbc:mysql://localhost:3306/user_registration
  username: root
  password: Goldenstar@123
  driver-class-name: com.mysql.cj.jdbc.Driver
 jpa:
  show-sql: true
  hibernate:
   ddl-auto: update
 devtools:
  livereload:
   enabled: true
 security:
    oauth2:
      client:
        registration: # Client name
          apiClientName:
           client-name: apiClientName
           client-id: api-client
           client-secret: secret
           provider: spring
           authorization-grant-type: authorization_code
           client-authentication-method: client_secret_basic
           #redirect-uri: "http://localhost:8085/login/oauth2/code/{registrationId}"
           redirect-uri: "http://localhost:8085/login/oauth2/code/apiClientName"
           #scope: profile,email,openid
           scope: profile
          api-client-authorization-code:
           provider: spring
           client-id: api-client
           client-secret: secret
           authorization-grant-type: authorization_code
           redirect-uri: "http://localhost:8085/authorized"
           #scope: profile,email,openid
           scope: profile
           client-name: api-client-authorization-code
        provider:
          spring:
            #issuer-uri: http://auth-server:9000
            issuer-uri: http://localhost:9000