server:
 port: 8085
 
spring:
 datasource:
  url: jdbc:mysql://localhost:3306/user_registration
  username: root
  password: Goldenstar@123
  driver-class-name: com.mysql.cj.jdbc.Driver
 jpa:
  show-sql: true
  hibernate:
   ddl-auto: update
 devtools:
  livereload:
   enabled: true
 security:
    oauth2:
     client:
      registration:
       google:
        client-id: 852560245449-07uajfkd44cb7cc06f6knspps4e5anq2.apps.googleusercontent.com
        client-secret: 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
       github:
        client-id: bbf5a8c0a34a64c1a23a
        client-secret: 455910fc9a5e5fb469f1c8491f4e2af735c26748